logging:
  level:
    root: DEBUG

spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  datasource:
    url: jdbc:postgresql://kurge-api.bitble.one:5432/bitble_kurse_dev
    username: postgres
    password: postgres


  mail:
    host: smtp.gmail.com
    port: 587
    username: hungtran6360
    password: weapsadpimnqtkfv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-circular-references: true
#  data:
#    mongodb:
#      uri: mongodb+srv://admin:admin@mongo-aufgabe-dev.671lr.mongodb.net/highland-mimic?retryWrites=true&w=majority
#      database: highland-mimic

server:
  port: 80
  servlet:
    context-path: /kurse/api

hibernate:
  globally_quoted_identifiers: true
